#!/usr/bin/env python3
"""Generate a C++ header that embeds the T113 Tuya bridge binary."""

from __future__ import annotations

import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BINARY = ROOT / "runtime" / "bin" / "cj96_tuya_demo"
OUTPUT = ROOT / "src" / "generated" / "TuyaBridgeEmbedded.h"


def main() -> int:
    data = BINARY.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/embed_tuya_bridge.py. Do not edit manually.",
        "static const unsigned char kEmbeddedTuyaBridge[] = {",
    ]
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(
        [
            "};",
            f"static const unsigned int kEmbeddedTuyaBridgeSize = {len(data)}U;",
            f'static const char kEmbeddedTuyaBridgeSha256[] = "{digest}";',
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines)
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="ascii") != content:
        OUTPUT.write_text(content, encoding="ascii", newline="\n")
    print(f"embedded={BINARY} size={len(data)} sha256={digest}")
    print(f"header={OUTPUT} size={OUTPUT.stat().st_size}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
